portfolio_comingsoon:
    path:     /index
    defaults: { _controller: PortfolioBundle:ComingSoon:index }
portfolio_index:
    path: /
    defaults:
      _controller: PortfolioBundle:Portfolio:index
