portfolio_comingsoon:
    path:     /
    defaults: { _controller: PortfolioBundle:ComingSoon:index }
portfolio_index:
    path: /index
    defaults:
      _controller: PortfolioBundle:Portfolio:index
