# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    PiiDev\UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    panel:
      entity:
        class:    PiiDev\UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
      pattern: ^/login$
      anonymous: true
    panel:
      pattern:   ^/panel
      anonymous: true
      provider: panel
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     portfolio_panel
    main:
      pattern: ^/
      anonymous: true

  access_control:
    - { path: ^/panel, roles: ROLE_ADMIN}
